
frequency: 12.5 # Hz
sec_remove: 4 # Time in seconds     -> 4 seconds?
sample_size : 10 # Time in seconds  -> 12 seconds?
sample_overlap : 50 # Overal in %   
dimensions : 3

# activity group
sedentary: [8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 21]          # 0
light_intensity: [0, 3, 4, 6, 7, 12, 20]                           # 1  moved standing related activities to light intensity
moderate_intensity: [1, 5, 23, 24]                                 # 2
vigorous_intensity: [2, 22]                                        # 3
other_group: [25, 26, 27, 28]                                      # 4
non_wear: [-3]                                                     # -2

# Peak finding algorithm
seed1 : {peakheight : 2.5, distance : 200, window_min: 150,  window_max: 650, start : 0, end : 1500}
seed2 : {peakheight : 1.5, distance : 200, window_min: 150,  window_max: 650, start : 0, end : 1500}
seed3 : {peakheight : 3.5, distance : 200, window_min: 150,  window_max: 650, start : 500, end : 1500}
seed4 : {peakheight : 3.5, distance : 200, window_min: 150,  window_max: 650, start : 1000, end : 2500}
seed5 : {peakheight : 2, distance : 300, window_min: 150,  window_max: 650, start : 0, end : 1500}
seed6 : {} # Seed6 files are all processed manually.
seed7 : {} # Seed7 files are skipped because of bad data.

data_cleaning_seeds : {CP1001_0 : seed1,
CP1002_0 : seed6,
CP1003_0 : seed1,
CP1004_0 : seed6,
CP1005_0 : seed6,
CP1006_0 : seed6,
CP1007_0 : seed5,
CP1008_0 : seed1,
CP1009_0 : seed1,
CP1010_0 : seed7,
CP1011_0 : seed2,
CP1012_0 : seed2,
CP1013_0 : seed3,
CP1014_0 : seed1,
CP1015_0 : seed1,
CP1016_0 : seed6,
CP1017_0 : seed1,
CP1018_0 : seed1,
CP1019_0 : seed1,
CP1020_0 : seed5,
CP2001_0 : seed7,
CP2002_0 : seed1,
CP2003_0 : seed1,
CP2004_0 : seed6,
CP2005_0 : seed2,
CP2006_0 : seed5,
CP2007_0 : seed6,
CP2008_0 : seed1,
CP2009_0 : seed1,
CP2010_0 : seed1,
HP01_0 : seed4,
HP02_0 : seed1,
HP03_0 : seed3,
HP03_1 : seed1,
HP04_0 : seed1,
HP04_1 : seed1,
HP05_0 : seed6,
HP05_1 : seed1,
HP07_0 : seed6,
HP08_0 : seed6,
HP08_1 : seed1,
HP09_0 : seed3,
HP10_0 : seed1,
HP10_1 : seed1,
HP11_0 : seed6,
HP11_1 : seed1,
HP12_0 : seed1,
HP13_0 : seed1,
HP14_0 : seed6,
HP15_0 : seed6,
HP16_0 : seed6,
HP16_1 : seed1,
HP17_0 : seed1,
HP18_0 : seed1,
HP19_0 : seed1,
HP19_1 : seed1,
HP20_0 : seed1,
HP21_0 : seed2,
HP22_0 : seed6,
HP23_0 : seed6,
HP24_0 : seed6,
HP25_0 : seed1,
HP26_0 : seed6,
HP27_0 : seed1,
HP28_0 : seed6,
HP29_0 : seed1,
HP30_0 : seed1,
HP31_0 : seed1
}


# frequency_factor: 10000 # The sensor prints timestamps based on the base oscillator of the sensor, this factor helps getting the right value in seconds
# diff_percent_data_label: 0.3
# minimal_file_size: 0 #10485760 # 10MB
# duration_threshold: 3             # Seconds
# shakes: 3                         # By subject to start-stop activity
# auto_find_peak: True              # Find peaks utomatically
# plot_start_signature: 100
# plot_end_signature: 2000
# use_corr_find_peak: False
# sampledTimeLowThreshold : 10      # seconds
# sampledTimeHighThreshold : 100    # seconds
# clean_daily_data: False
# pain_score_time_point: [6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
